### ISSUE TITLE
[TODO] 待辦事項

### ISSUE THREAD

**Issue by leoli0605** [leoli0605/vscode-bettergpt-extension#1]
## Major
- [x] 加入類似 GitHub Copilot 的互動式對話框，讓使用者可以使用按鈕 ~~`replace`~~ or ~~`insert`~~ 處理後的結果
  - 使用 [VSCode Comment API](https://github.com/microsoft/vscode-extension-samples/tree/main/comment-sample) 實作
- [ ] 參考 [vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker) 的類似對話框設計做此專案的對話框優化
- [x] 預設就將結果複製
- [ ] 修復一些 `comment` 使用不便的地方
  - 添加 `close` 與快捷鍵 `esc` 來關閉對話框
  - 產生下一個對話框時則將前一個對話框關閉
- [ ] 將顯示的 watcher 加入 timeout 自動關閉時間
- [ ] 添加快捷鍵
  - `replace`
  - `insert`
  - `translate`
  - `grammar`
- [ ] 加入 `API` 為空的提示
- [ ] 安裝後若 `API` 為空則跳轉到設定
- [ ] 在 `terminal` 加入 `translate` 及 `grammar`
- [ ] 使用 DALL-E 根據使用者選取的內容產生圖片 (參考[連結](https://github.com/ismailkasan/chat-gpt-vscode-extension))

## Minor
- [ ] 加入 `BetterChatGPT` VSCode 版本 GUI (參考[連結](https://bettergpt.chat/) / [原始碼](https://github.com/ztjhz/BetterChatGPT))
- [ ] 加入圖片 `edit` 拓展/轉換成各種解析度的功能
- [x] 加入 `icon`
- [ ] 優化 `README.md`
- [ ] 維護 `CHANGELOG.md`
- [ ] 加入客製化設定
  - `model` 選擇
  - `prompt` 自定義

---

- [參考連結 1](https://github.com/linexjlin/GPTs/tree/main?fbclid=IwAR1ertN-0-q2zLQch1uS4KigP98bgudKBpvT_5Dbcs9KqktCG3CCF80TDD4)
